language: node_js

node_js:
  - "10"

cache: yarn

before_install:
  - wget  -O ./firebase.conf.js "https://$FIREBASE_ID.firebaseapp.com/__/firebase/init.js"
  - sed -i "1d; s/firebase.initializeApp(/module.exports = /; s/});/}/; s/\t\"/  /g; s/\":/:/g; s/\"/\'/g; \$s/$/\n/" firebase.conf.js
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn
  - yarn add global @quasar/cli

script:
  - quasar build

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "$FIREBASE_ID"
  on:
    branch: prod

notifications:
  email: false
