language: node_js

node_js:
  - "10"

cache: yarn

before_install:
  - cp firebase.conf.example.js firebase.conf.js
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn
  - yarn add global @quasar/cli

script:
  - quasar build

deploy:
  if: branch = prod
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "madin-darut-taqwa"

notifications:
  email: false
